DROP DATABASE COMERCIO;


CREATE DATABASE COMERCIO;

USE COMERCIO;


-- CRIANDO TABELA DE CLIENTES:

CREATE TABLE CLIENTES(

	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR (30) NOT NULL,
	SEXO ENUM ('M', 'F') NOT NULL,
	EMAIL VARCHAR(30) UNIQUE,
	CPF VARCHAR (15) UNIQUE

);

-- CRIANDO TABELA DE ENDEREÇOS:



CREATE TABLE ENDERECOS(

	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO VARCHAR(2) NOT NULL,
	ID_CLIENTE INT UNIQUE,
	FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTES(IDCLIENTE)

);

-- CRIANDO TABELA TELEFONE

CREATE TABLE TELEFONES (

	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('RES', 'COM', 'CEL') NOT NULL,
	NUMERO VARCHAR(10)NOT NULL,
	ID_CLIENTE INT, 
	FOREIGN KEY(ID_CLIENTE)REFERENCES CLIENTES(IDCLIENTE)
	
);